# Generated by Django 4.1 on 2022-12-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='fecha_contrato',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='fecha_contrato',
            field=models.DateField(null=True),
        ),
    ]
