# Generated by Django 4.1 on 2022-12-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_admin_fecha_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_medico',
            name='diagnostico',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='control_medico',
            name='tratamiento',
            field=models.TextField(max_length=300),
        ),
    ]
