# Generated by Django 4.1 on 2022-12-20 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_servicio_tipo_pago_alter_peticionresidente_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
