# Generated by Django 4.1 on 2022-12-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_detallefactura_servicio_alter_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='usuario.factura'),
        ),
    ]
