# Generated by Django 4.1.1 on 2022-12-06 00:53

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_control_medico_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='control_medico',
            name='fecha_control',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('"\x08[0-9|.]{1,10}\\-[K|k|0-9]"gmi', message='No debe tener puntos y con guion')]),
        ),
    ]
