# Generated by Django 4.1.1 on 2022-12-06 20:58

import django.core.validators
from django.db import migrations, models
import usuario.validations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El rut debe de ser sin puntos y con guion', regex='^[0-9]+-[0-9kK]{1}$'), usuario.validations.ValidacionRut]),
        ),
    ]
